## Create a Number Sum Dataset

This dataset has two features—a pair of numbers—and a target value—the sum of those two numbers.

Note that this is not actually a good use of deep learning. At the end of our training loop, the model still doesn't know how to add 3 + 7! The idea here is to use a simple example so it's easy to evaluate the model's performance.

In [19]:
import torch  # Import PyTorch library
import torch.nn as nn  # Import neural network module
import torch.optim as optim  # Import optimization module
from torch.utils.data import Dataset, DataLoader  # Import Dataset and DataLoader classes
                                                                                                                                                                                                                                     
class NumberSumDataset(Dataset):  # Custom dataset for number pairs and their sums
    def __init__(self, data_range=(1, 10)):  # Initialize with a range of numbers
        self.numbers = list(range(data_range[0], data_range[1]))  # List of numbers in range

    def __getitem__(self, index):  # Get item at index, creating all combinations
        number1 = float(self.numbers[index // len(self.numbers)])  # First number from integer division
        number2 = float(self.numbers[index % len(self.numbers)])  # Second number from modulo
        return torch.tensor([number1, number2]), torch.tensor([number1 + number2])  # Return inputs and sum as tensors

    def __len__(self):  # Return total number of combinations
        return len(self.numbers) ** 2  # Square of the number of numbers

## Inspect the Dataset

In [20]:
dataset = NumberSumDataset(data_range=(1, 100))  # Create dataset with numbers 1 to 99

for i in range(5):  # Loop over first 5 samples
    print(dataset[i])  # Print each sample
# (tensor([1., 1.]), tensor([2.]))  # Sample 0: 1+1=2
# (tensor([1., 2.]), tensor([3.]))  # Sample 1: 1+2=3
# (tensor([1., 3.]), tensor([4.]))  # Sample 2: 1+3=4
# (tensor([1., 4.]), tensor([5.]))  # Sample 3: 1+4=5
# (tensor([1., 5.]), tensor([6.]))  # Sample 4: 1+5=6

(tensor([1., 1.]), tensor([2.]))
(tensor([1., 2.]), tensor([3.]))
(tensor([1., 3.]), tensor([4.]))
(tensor([1., 4.]), tensor([5.]))
(tensor([1., 5.]), tensor([6.]))


## Define a Simple Model

In [21]:
class MLP(nn.Module):  # Define a simple Multi-Layer Perceptron model
    def __init__(self, input_size):  # Constructor with input size
        super(MLP, self).__init__()  # Call parent constructor
        self.hidden_layer = nn.Linear(input_size, 128)  # Hidden layer: input_size to 128 neurons
        self.output_layer = nn.Linear(128, 1)  # Output layer: 128 to 1 neuron
        self.activation = nn.ReLU()  # ReLU activation function

    def forward(self, x):  # Forward pass
        x = self.activation(self.hidden_layer(x))  # Apply hidden layer and activation
        return self.output_layer(x)  # Apply output layer

## Instantiate Components Needed for Training

In [22]:
dataset = NumberSumDataset(data_range=(0, 100))  # Dataset with numbers 0 to 99
dataloader = DataLoader(dataset, batch_size=100, shuffle=True)  # DataLoader with batch size 100, shuffled
model = MLP(input_size=2)  # Model with 2 inputs
loss_function = nn.MSELoss()  # Mean Squared Error loss
optimizer = optim.Adam(model.parameters(), lr=0.001)  # Adam optimizer with learning rate 0.001

## Create a Training Loop

In [ ]:
for epoch in range(10):  # Loop over 10 epochs
    total_loss = 0.0  # Initialize total loss for the epoch
    for number_pairs, sums in dataloader:  # Iterate over batches
        predictions = model(number_pairs)  # Forward pass: get predictions
        loss = loss_function(predictions, sums)  # Calculate loss between predictions and targets
        loss.backward()  # Backpropagate to compute gradients
        optimizer.step()  # Update model parameters
        optimizer.zero_grad()  # Reset gradients for next batch
        total_loss += loss.item()  # Accumulate loss
    # Print the loss for this epoch
    print("Epoch {}: Sum of Batch Losses = {:.5f}".format(epoch, total_loss))  # Print epoch loss
    # Epoch 0: Sum of Batch Losses = 118.82360
    # Epoch 1: Sum of Batch Losses = 39.75702
    # Epoch 2: Sum of Batch Losses = 2.16352
    # Epoch 3: Sum of Batch Losses = 0.25178
    # Epoch 4: Sum of Batch Losses = 0.22843
    # Epoch 5: Sum of Batch Losses = 0.19182
    # Epoch 6: Sum of Batch Losses = 0.15507
    # Epoch 7: Sum of Batch Losses = 0.07789
    # Epoch 8: Sum of Batch Losses = 0.06329
    # Epoch 9: Sum of Batch Losses = 0.04936

Epoch 0: Sum of Batch Losses = 99135.20716
Epoch 1: Sum of Batch Losses = 782.40139
Epoch 2: Sum of Batch Losses = 121.94491
Epoch 3: Sum of Batch Losses = 16.53745
Epoch 4: Sum of Batch Losses = 7.29043
Epoch 5: Sum of Batch Losses = 4.75736
Epoch 6: Sum of Batch Losses = 3.51881
Epoch 7: Sum of Batch Losses = 2.71003
Epoch 8: Sum of Batch Losses = 2.11694
Epoch 9: Sum of Batch Losses = 1.63503
Epoch 10: Sum of Batch Losses = 1.29607
Epoch 11: Sum of Batch Losses = 1.05477
Epoch 12: Sum of Batch Losses = 0.88231
Epoch 13: Sum of Batch Losses = 0.75304
Epoch 14: Sum of Batch Losses = 0.65851
Epoch 15: Sum of Batch Losses = 0.57994
Epoch 16: Sum of Batch Losses = 0.52529
Epoch 17: Sum of Batch Losses = 0.47321
Epoch 18: Sum of Batch Losses = 0.43537
Epoch 19: Sum of Batch Losses = 0.40246


### Try the Model Out


In [24]:
# Test the model on 3 + 7
model(torch.tensor([3.0, 7.0]))  # Predict sum of 3 and 7
# tensor([10.1067], grad_fn=<AddBackward0>)  # Approximate result (close to 10)

tensor([10.0070], grad_fn=<ViewBackward0>)